### ISSUE TITLE
babel-plugin-pull

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream-docs#30]
I created [this Babel plugin](https://github.com/jamen/babel-plugin-pull) inspired from https://github.com/pull-stream/pull-stream/issues/90 that lets you use a "pipe operator":

```js
oscillator({ wave: 'sine' })
| gain(0.5)
| speaker()
```

One of the more major benefits over the other plugins is you can compose things together in a really nice way:

```js
// Create a source
const baz = foo() | bar()

// Use it
baz 
| qux()
| oof()
```

I was wondering where I should list this in the docs.

**Comment by dominictarr** [comment]
under a *magic* section? ;)
but, hmm, I guess everything else in the docs pretty much returns a pull-stream in one way or another, so this probably should be a misc section or something like that.

**Comment by ahdinosaur** [comment]
this is rad! maybe _sugar_? or maybe the existing _interop_ section? i'm happy with whatever you think @jamen. :+1:

**Comment by jamen** [comment]
okay I did "interop" seemed fine :smile:

**Comment by dominictarr** [comment]
too much sugar is bad for your health.
