### ISSUE TITLE
pull-await: await syntax on promises in pull streams

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream-docs#5]
I have made a pull-stream module, but I'm confused about adding it.  I don't know if there is specific requirements and how to add it to the docs here.

You can check it at [jamen/pull-stream](https://github.com/jamen/pull-await).  It basically ends up looking like this inside of pull-stream:

``` javascript
var await = require('pull-await');

pull(
  // Pass any regular data or promises
  pull.values([
    'hello',
    Promise.resolve('world').delay(250),
    request('https://registry.npmjs.org/pull-stream/0.1.0')
  ]),

  await, // use pull-await to resolve them.

  pull.collect(function(err, data) {
    console.log(data);
  });
);
```

This is my first module, pretty new, but it is awesome so far.  :)

**Comment by dominictarr** [comment]
all you need to do is make a PR to this module, following these instructions https://github.com/pull-stream/pull-stream-docs#adding-a-module-to-the-ecosystem

see this PR for example: https://github.com/pull-stream/pull-stream-docs/pull/4

**Comment by jamen** [comment]
Thank you.
